spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: search-indexer
      client-id: search-indexer-${random.uuid}
application:
  kafka:
    consumer:
      novel-event:
        topic: "novel-event"
      rating-event:
        topic: "novel-rating-event"
  elasticsearch:
    index: "novels"
  rest:
    user-api:
      url: ${USER_API_URL}