spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: search-indexer
      client-id: search-indexer-${random.uuid}
application:
  kafka:
    novel:
      topic: "novel-event"
    novel-rating:
      topic: "novel-rating-event" # TODO add consumer
  elasticsearch:
    index: "novels"
