application:
  kafka:
    producer:
      rating-command:
        topic: "novel-rating-command"

spring:
  application:
    name: rating-api
  data:
    redis:
      url: redis://localhost:6379
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      client-id: "rating-api"

management:
  otlp:
    tracing:
      endpoint: ${TRACING_URL}
  tracing:
    sampling:
      probability: 1.0