application:
  kafka:
    producer:
      rating-command:
        topic: "novel-rating-command"

spring:
  application:
    name: rating-api
  data:
    redis:
      url: redis://localhost:6379
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      client-id: "rating-api"
