spring:
  shell:
    interactive:
      enabled: true
  h2:
    console:
      enabled: true
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:h2:mem:library
    driverClassName: org.h2.Driver
    username: sa
    password:
  data:
    mongodb:
      uri: mongodb://localhost:27017/library?retryWrites=false
mongock:
  transactional: false
  runner-type: InitializingBean
  migration-scan-package:
    - ru.otus.hw.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local