spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/jwks
  datasource:
    url: jdbc:h2:mem:library
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
app:
  token-ttl: 3600
  token-issuer: http://localhost:8080
  key-id: 586b7a7d-6fa7-4044-9a71-685e05d4ef80