spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
mongock:
  runner-type: InitializingBean
  migration-scan-package:
    - ru.otus.hw.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
app:
  token-ttl: 3600
  token-issuer: http://localhost:8080
  key-id: 586b7a7d-6fa7-4044-9a71-685e05d4ef80