services:
  user-api:
    image: user-api:1.0.0
    container_name: user-api
    pull_policy: missing
    ports:
      - "8081:8080"
    environment:
      - TRACING_URL=http://jaeger:4318/v1/traces
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-postgres:5432/user
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
    depends_on:
      - user-postgres

  user-postgres:
    image: postgres:17.4
    container_name: user-postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=user