environments:
  local:

---

releases:
  - name: user-api
    namespace: user
    chart: ../../../deploy/charts/service
    values:
      - ./values/user-api/{{ $.Environment.Name }}.yaml
    needs:
      - user-postgres

  - name: user-postgres
    namespace: user
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: 16.4.15
    values:
      - ./values/user-postgres/{{ $.Environment.Name }}.yaml