environments:
  local:

---

helmDefaults:
  verify: false
  # wait for k8s resources via --wait. (default false)
  wait: true
  # time in seconds to wait for any individual Kubernetes operation (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness) (default 300)
  timeout: 300
  # performs pods restart for the resource if applicable (default false)
  recreatePods: false
  # forces resource update through delete/recreate if needed (default false)
  force: false
  # when using helm 3.2+, automatically create release namespaces if they do not exist (default true)
  createNamespace: false

releases:
  - name: postgresql
    namespace: default
    chart: ./charts/postgresql
    values:
      - ./values/postgresql/{{ $.Environment.Name }}.yaml
    wait: true
  - name: app
    namespace: default
    chart: ./charts/app
    values:
      - ./values/app/{{ $.Environment.Name }}.yaml
    wait: true