spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
application:
  public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt/Dnh8tp1y+yBV6XItMSb8kzyvwojGZU4d9V9qvoroPKZDQ4LGfZdz8Xdsc84AqZSIizxV4griM1xJ/WyoVuRQgErEQG5xeEOyqVZ4CEbRuf1Ajq/Be4SK9hcNNCIE7k3HubzRIx0D9GnvrhOLHf5pJ4AnbQyX/lXZxKSW+QE3j9VV67k4JGt2Y5kx5TiVDlfKNOwsTDLakjUFRt7Gfo0fHhJbybelkgECbS+HeKSUx25u6rNo2Nj0J7DskRcPWZSpQ3MKh+iBAa1atSruridJjw44qKI1ZkRwuSdNblNhEg7K5jwXXLV0eF2aLxT4517NYKLnu0jHbrihjWy/k7mwIDAQAB"
  api-routes:
    - id: "user"
      prefix: "/user"
      uri: ${USER_API_URI}
    - id: "novel"
      prefix: "/novel"
      uri: ${NOVEL_API_URI}