services:
  rating-api:
    image: rating-api:1.0.0
    container_name: rating-api
    pull_policy: missing
    ports:
      - "8084:8080"
    environment:
      - TRACING_URL=http://jaeger:4318/v1/traces
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATA_REDIS_HOST=rating-redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - rating-redis

  rating-consumer:
    image: rating-consumer:1.0.0
    container_name: rating-consumer
    pull_policy: missing
    environment:
      - TRACING_URL=http://jaeger:4318/v1/traces
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATA_REDIS_HOST=rating-redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - rating-redis

  rating-redis:
    image: redis:alpine
    container_name: rating-redis
    ports:
      - "6374:6379"
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]