spring:
  application:
    name: search-api

management:
  otlp:
    tracing:
      endpoint: ${TRACING_URL}
  tracing:
    sampling:
      probability: 1.0
  server:
    port: 90
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

application:
  elasticsearch:
    host: ${ELASTICSEARCH_HOST}
    port: ${ELASTICSEARCH_PORT}
    index: "novels"
