environments:
  local:

---

helmDefaults:
  verify: false
  wait: false
  timeout: 300
  recreatePods: false
  force: false
  createNamespace: true

helmfiles:
  - ../services/user/deploy/helmfile.yaml
  - ../services/gateway/deploy/helmfile.yaml
  - ../services/novel/deploy/helmfile.yaml
  - ../services/rating/deploy/helmfile.yaml
  - ../services/search/deploy/helmfile.yaml

releases:
  - name: jaeger
    namespace: jaeger
    chart: jaegertracing/jaeger
    version: 3.4.1
    values:
      - ./values/jaeger/{{ $.Environment.Name }}.yaml

  - name: kafka
    namespace: kafka
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: 32.1.1
    values:
      - ./values/kafka/{{ $.Environment.Name }}.yaml

  - name: loki
    namespace: loki
    chart: oci://registry-1.docker.io/bitnamicharts/grafana-loki
    version: 4.7.6
    values:
      - ./values/loki/{{ $.Environment.Name }}.yaml

  - name: grafana
    namespace: grafana
    chart: oci://registry-1.docker.io/bitnamicharts/grafana
    version: 11.6.1
    values:
      - ./values/grafana/{{ $.Environment.Name }}.yaml

  - name: prometheus
    namespace: prometheus
    chart: oci://registry-1.docker.io/bitnamicharts/prometheus
    version: 1.4.9
    values:
      - ./values/prometheus/{{ $.Environment.Name }}.yaml