environments:
  local:

---

releases:
  - name: gateway-api
    namespace: gateway
    chart: ../../../deploy/charts/service
    values:
      - ./values/gateway-api/{{ $.Environment.Name }}.yaml
    needs:
      - gateway-redis

  - name: gateway-redis
    namespace: gateway
    chart: oci://registry-1.docker.io/bitnamicharts/redis
    version: 20.11.4
    values:
      - ./values/gateway-redis/{{ $.Environment.Name }}.yaml