spring:
  application:
    name: novel-outbox
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      client-id: "novel-outbox"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: novel

management:
  otlp:
    tracing:
      endpoint: ${TRACING_URL}
  tracing:
    sampling:
      probability: 1.0