environments:
  local:

---

releases:
  - name: search-api
    namespace: search
    chart: ../../../deploy/charts/service
    values:
      - ./values/search-api/{{ $.Environment.Name }}.yaml
    needs:
      - search-elasticsearch

  - name: search-indexer
    namespace: search
    chart: ../../../deploy/charts/service
    values:
      - ./values/search-indexer/{{ $.Environment.Name }}.yaml
    needs:
      - search-elasticsearch

  - name: search-elasticsearch
    namespace: search
    chart: oci://registry-1.docker.io/bitnamicharts/elasticsearch
    version: 21.4.9
    values:
      - ./values/search-elasticsearch/{{ $.Environment.Name }}.yaml