spring:
  application:
    name: novel-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: novel
    redis:
      host: localhost
      port: 6379
application:
  kafka:
    producer:
      novel-event:
        topic: "novel-event"
  redis:
    idempotency-processing-ttl: 2m
    idempotency-cache-ttl: 24h

management:
  otlp:
    tracing:
      endpoint: ${TRACING_URL}
  tracing:
    sampling:
      probability: 1.0
  server:
    port: 9090
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"