fullnameOverride: jaeger

allInOne:
  enabled: true
  extraEnv:
    - name: COLLECTOR_OTLP_ENABLED
      value: "true"

provisionDataStore:
  cassandra: false

storage:
  type: memory

agent:
  enabled: false

collector:
  enabled: false

query:
  enabled: false