spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: rating-consumer
      client-id: rating-consumer-${random.uuid}
application:
  kafka:
    topic: "novel-rating-command"
    ttl: 24h