spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: rating-consumer
      client-id: rating-consumer-${random.uuid}
  data:
    redis:
      url: redis://localhost:6379
application:
  kafka:
    consumer:
      rating-command:
        topic: "novel-rating-command"
        idempotency-key-ttl: 24h
    producer:
      rating-event:
        topic: "novel-rating-event"
