services:
  novel:
    image: localhost:5000/novel:1.0.0
    pull_policy: always
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=novel_mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=novel
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=admin
    depends_on:
      - novel_mongo
  novel_mongo:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: novel
    ports:
      - '27012:27017'
