environments:
  local:

---

releases:
  - name: novel-api
    namespace: novel
    chart: ../../../deploy/charts/service
    values:
      - ./values/novel-api/{{ $.Environment.Name }}.yaml
    needs:
      - novel-mongodb
      - novel-redis

  - name: novel-outbox
    namespace: novel
    chart: ../../../deploy/charts/service
    values:
      - ./values/novel-outbox/{{ $.Environment.Name }}.yaml
    needs:
      - novel-mongodb

  - name: novel-mongodb
    namespace: novel
    chart: oci://registry-1.docker.io/bitnamicharts/mongodb
    version: 16.4.10
    values:
      - ./values/novel-mongodb/{{ $.Environment.Name }}.yaml

  - name: novel-redis
    namespace: novel
    chart: oci://registry-1.docker.io/bitnamicharts/redis
    version: 20.11.4
    values:
      - ./values/novel-redis/{{ $.Environment.Name }}.yaml