fullnameOverride: rating-api
replicaCount: 1

image:
  repository: rating-api
  pullPolicy: IfNotPresent
  tag: "1.0.0"

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: probe
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: probe
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

autoscaling:
  enabled: false

env:
  - name: TRACING_URL
    value: "http://jaeger-collector.default:4318/v1/traces"
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: "kafka.default:9092"
  - name: SPRING_DATA_REDIS_URL
    value: "redis://rating-redis-master.rating:6379"