spring:
  data:
    mongodb:
#      host: ${MONGO_HOST:localhost}
#      port: ${MONGO_PORT:27017}
#      database: ${MONGO_DATABASE}
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
server:
  port: 8081