### Get aggregated novel rating
GET {{baseUrl}}/rating/novels/{{novelId}}
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

### Rate novel
POST {{baseUrl}}/rating/novels/{{novelId}}/ratings
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json
X-Idempotency-Key: 1f90eb21-6672-4e2d-bbc0-58188ee45b7b
#X-Idempotency-Key: {{$random.uuid}}

{
  "rating": 8
}