services:
  rating-api:
    image: localhost:5000/rating-api:1.0.0
    pull_policy: always
    ports:
      - "8084:8080"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATA_REDIS_URL=redis://rating-redis:6379
    depends_on:
      - rating-redis

  rating-consumer:
    image: localhost:5000/rating-consumer:1.0.0
    pull_policy: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATA_REDIS_URL=redis://rating-redis:6379
    depends_on:
      - rating-redis

  rating-redis:
    image: redis:alpine
    ports:
      - "6374:6379"
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]