spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/tokens
server:
  port: 7777

application:
  api-routes:
    - id: "user"
      prefix: "/user"
      uri: "http://localhost:8080"