services:
  user:
    image: localhost:5000/user:1.0.0
    pull_policy: always
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_postgres:5432/user
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
    depends_on:
      - user_postgres
  user_postgres:
    image: postgres:17.4
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=user
