services:
  app:
    image: localhost:5000/user:latest
    pull_policy: always
    ports:
      - "8081:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DATABASE=user
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=user
